// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnXXXiC-VAcaKSW3C-crAIZTCLxjsNLsI',
    appId: '1:238762241401:web:4ad37e34495dae156d93a8',
    messagingSenderId: '238762241401',
    projectId: 'lifelink-c0abc',
    authDomain: 'lifelink-c0abc.firebaseapp.com',
    storageBucket: 'lifelink-c0abc.firebasestorage.app',
    measurementId: 'G-JGHRRPLM4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ-RZfRLpXOl1aJ-m_Y_XT2PiQKDfnPQY',
    appId: '1:238762241401:android:724e62a149b32c3f6d93a8',
    messagingSenderId: '238762241401',
    projectId: 'lifelink-c0abc',
    storageBucket: 'lifelink-c0abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-SKratr5HTm2UUBBY_k4ROwgNXDSHRDk',
    appId: '1:238762241401:ios:e04c2948cde6a4d96d93a8',
    messagingSenderId: '238762241401',
    projectId: 'lifelink-c0abc',
    storageBucket: 'lifelink-c0abc.firebasestorage.app',
    iosBundleId: 'com.example.lifelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-SKratr5HTm2UUBBY_k4ROwgNXDSHRDk',
    appId: '1:238762241401:ios:e04c2948cde6a4d96d93a8',
    messagingSenderId: '238762241401',
    projectId: 'lifelink-c0abc',
    storageBucket: 'lifelink-c0abc.firebasestorage.app',
    iosBundleId: 'com.example.lifelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnXXXiC-VAcaKSW3C-crAIZTCLxjsNLsI',
    appId: '1:238762241401:web:f7c0abd0e290b3bc6d93a8',
    messagingSenderId: '238762241401',
    projectId: 'lifelink-c0abc',
    authDomain: 'lifelink-c0abc.firebaseapp.com',
    storageBucket: 'lifelink-c0abc.firebasestorage.app',
    measurementId: 'G-F1ZMS22Y7H',
  );
}
