import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'screens/donor/donor_dashboard.dart';
import 'firebase_options.dart'; // This will be generated by flutterfire

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const LifeLinkApp());
}

class LifeLinkApp extends StatelessWidget {
  const LifeLinkApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'LifeLink',
      home: DonorDashboard(),
    );
  }
}
